language: node_js
node_js:
- "node"
- "lts/*"
cache:
  yarn: true
  directories:
  - node_modules
addons:
  apt:
    packages:
    - sshpass
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
script:
- yarn build
- yarn lint
after_success:
- cd public
- sshpass -e sftp -o StrictHostKeyChecking=no -r -P $SSH_PORT $SSH_USER@$SSH_HOST:$SSH_PATH <<< 'put -r .'
