backend:
  name: github
  repo: simonyiszk/mvk-web
  branch: master
media_folder: static/assets/uploads
public_folder: /assets/uploads
collections:
  - name: news
    label: News
    folder: src/pages/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Publish date", name: "date", widget: "datetime"}
      - {label: "Featured image", name: "thumbnail", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: teams
    label: Teams
    folder: src/pages/teams
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "E-mail", name: "email", widget: "string", required: false}
      - {label: "Color", name: "color", widget: "string", required: false}
      - {label: "Featured image", name: "thumbnail", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: highlights
    label: Highlights
    folder: src/pages
    create: false
    delete: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: data
    label: Data
    create: false
    delete: false
    editor:
      preview: false
    files:
      - name: menu
        label: Menu
        file: src/data/menu.json
        fields:
          - name: items
            label: Items
            widget: list
            fields:
              - {label: "URL", name: "url", widget: "string"}
              - {label: "Text", name: "text", widget: "string"}
      - name: cover-images
        label: Cover images
        file: src/data/cover-images.json
        fields:
          - {label: "Default", name: "defaultImage", widget: "image"}
          - {label: "Home page", name: "homePageImage", widget: "image"}
          - {label: "Not found page", name: "notFoundPageImage", widget: "image"}
          - {label: "Teams page", name: "teamsPageImage", widget: "image"}
          - {label: "Events page", name: "eventsPageImage", widget: "image"}
          - {label: "Gallery page", name: "galleryPageImage", widget: "image"}
          - {label: "Sponsors page", name: "sponsorsPageImage", widget: "image"}
      - name: events
        label: Events
        file: src/data/events.json
        fields:
          - name: events
            label: Events
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Start date", name: "start", widget: "datetime"}
              - {label: "End date", name: "end", widget: "datetime"}
      - name: sponsors
        label: Sponsors
        file: src/data/sponsors.json
        fields:
          - name: sponsors
            label: Sponsors
            widget: list
            fields:
              - {label: "Name", name: "name", widget: "string"}
              - {label: "Website", name: "website", widget: "string"}
              - {label: "Logo", name: "logo", widget: "image"}
              - {label: "Importance", name: "importance", widget: "number", default: 6, valueType: "int", min: 1, max: 12}
      - name: site-settings
        label: Site settings
        file: site-settings.json
        fields:
          - name: siteMetadata
            label: Site metadata
            widget: object
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Address (URL)", name: "siteAddressURL", widget: "string"}
              - {label: "Address (pretty)", name: "siteAddressPretty", widget: "string"}
              - {label: "Telephone (URL)", name: "siteTelephoneURL", widget: "string"}
              - {label: "Telephone (pretty)", name: "siteTelephonePretty", widget: "string"}
              - {label: "E-mail", name: "siteEmailURL", widget: "string"}
              - {label: "Facebook (URL)", name: "siteFacebookURL", widget: "string"}
              - {label: "GitHub (URL)", name: "siteGitHubURL", widget: "string"}
