backend:
  name: github
  repo: simonyiszk/mvk-web
  branch: master
media_folder: static/assets/uploads
public_folder: /assets/uploads
collections:
  - name: news
    label: News
    folder: src/pages/news
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "Publish date", name: "date", widget: "datetime"}
      - {label: "Featured image", name: "thumbnail", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: teams
    label: Teams
    folder: src/pages/teams
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", required: false}
      - {label: "E-mail", name: "email", widget: "string", required: false}
      - {label: "Color", name: "color", widget: "string", required: false}
      - {label: "Featured image", name: "thumbnail", widget: "image", required: false}
      - {label: "Excerpt", name: "excerpt", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: highlights
    label: Highlights
    folder: src/pages
    create: false
    delete: false
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: data
    label: Data
    create: false
    delete: false
    editor:
      preview: false
    files:
      - name: events
        label: Events
        file: src/pages/events/hu.json
        fields:
          - name: events
            label: Events
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Start date", name: "start", widget: "datetime"}
              - {label: "End date", name: "end", widget: "datetime"}
      - name: "site-settings"
        label: "Site settings"
        file: "site-settings.json"
        fields:
          - name: siteMetadata
            label: "Site metadata"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Address (URL)", name: "siteAddressURL", widget: "string"}
              - {label: "Address (pretty)", name: "siteAddressPretty", widget: "string"}
              - {label: "Telephone (URL)", name: "siteTelephoneURL", widget: "string"}
              - {label: "Telephone (pretty)", name: "siteTelephonePretty", widget: "string"}
              - {label: "E-mail", name: "siteEmailURL", widget: "string"}
              - {label: "Facebook (URL)", name: "siteFacebookURL", widget: "string"}
              - {label: "GitHub (URL)", name: "siteGitHubURL", widget: "string"}
      - name: "test-site-settings"
        label: "Test site settings"
        file: "test-site-settings.json"
        fields:
          - name: siteMetadata
            label: "Site metadata"
            widget: list
            fields:
              - {label: "Title", name: "title", widget: "string"}
